version: '3.5'
services:
  devbox:
    container_name: devbox
    image: devbox
    volumes:
      - ${DEV_HOME_PATH:-C:\portable\home}:/home/dantin
      - ${DEV_DATA_PATH:-C:\portable\data}:/data
    ports:
      - "2222:22"
    networks:
      - dev_zone

networks:
  dev_zone:
    driver: bridge
